# Generated by Django 4.0.4 on 2026-03-04 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jid', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('vacancy', models.PositiveIntegerField()),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='hiring.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Police', 'Police'), ('Employer', 'Employer'), ('Worker', 'Worker')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('date_of_birth', models.DateField()),
                ('languages_known', models.CharField(max_length=200)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to='hiring.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NOC',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_nocs', to='hiring.userprofile')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='noc', to='hiring.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(max_length=100)),
                ('insurance_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='hiring.worker')),
            ],
        ),
        migrations.AddField(
            model_name='contractor',
            name='login',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to='hiring.userprofile'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('rqid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hiring.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hiring.worker')),
            ],
            options={
                'unique_together': {('job', 'worker')},
            },
        ),
    ]
